# Generated by Django 3.1.2 on 2020-11-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_profile_first_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='assigned_class',
            new_name='classes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='post',
        ),
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_login',
            field=models.BooleanField(default=True, max_length=100),
        ),
    ]
