# Generated by Django 3.1.2 on 2020-11-19 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_auth', '0006_auto_20201116_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subject',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('a', 'Mr.'), ('b', 'Ms.'), ('c', 'Mrs.')], max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='Data_Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.PositiveSmallIntegerField(null=True)),
                ('subject', models.CharField(choices=[('a', 'aa'), ('a', 'aa')], max_length=4)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
