# Generated by Django 3.1.2 on 2020-11-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_auto_20201119_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='data_permission',
            name='Class',
            field=models.PositiveSmallIntegerField(choices=[('a', 'choice1'), ('b', 'choice2'), ('c', 'choice3')], null=True),
        ),
        migrations.AlterField(
            model_name='data_permission',
            name='subject',
            field=models.CharField(choices=[('a', 'subjects1'), ('b', 'subjects2'), ('c', 'subjects3')], max_length=4),
        ),
    ]
