# Generated by Django 3.1.2 on 2020-11-28 17:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_auth', '0008_auto_20201119_1721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Employee',
        ),
        migrations.RenameModel(
            old_name='Data_Permission',
            new_name='Permissions',
        ),
        migrations.RenameField(
            model_name='permissions',
            old_name='Class',
            new_name='classes',
        ),
        migrations.RenameField(
            model_name='permissions',
            old_name='subject',
            new_name='subjects',
        ),
    ]
