# Generated by Django 3.1.2 on 2020-12-22 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_auth', '0009_auto_20201128_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='classes',
            field=models.CharField(choices=[('m', 'choice1'), ('n', 'choice2'), ('o', 'choice3')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='subjects',
            field=models.CharField(choices=[('p', 'subjects1'), ('q', 'subjects2'), ('r', 'subjects3')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
