# Generated by Django 3.1.4 on 2020-12-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_auto_20201230_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='classes',
            field=models.CharField(choices=[('m', 'choice1'), ('n', 'choice2'), ('o', 'choice3')], default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permissions',
            name='subjects',
            field=models.CharField(choices=[('p', 'subjects1'), ('q', 'subjects2'), ('r', 'subjects3')], default=0, max_length=30),
            preserve_default=False,
        ),
    ]
