# Generated by Django 3.1.4 on 2021-01-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Profile',
            new_name='Student',
        ),
    ]
