# Generated by Django 3.1.4 on 2021-01-07 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210107_1052'),
        ('classes', '0002_auto_20210107_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='CLass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.classes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='subject_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_1', to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_2', to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_3', to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_4', to='accounts.subject'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
