# Generated by Django 3.1.4 on 2021-01-10 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.profile')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.class')),
                ('subject', models.ManyToManyField(to='class_app.Subject')),
            ],
        ),
    ]
