# Generated by Django 3.2.4 on 2021-08-15 15:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0003_alter_departmentdetail_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('Monday', 1), ('Tuesday', 2), ('Wednesday', 3), ('Thursday', 4), ('Friday', 5), ('Saturday', 6)], max_length=10)),
                ('slot', models.IntegerField(validators=[django.core.validators.MaxValueValidator('10'), django.core.validators.MinValueValidator('1')])),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DEPARTMENT', to='department.departmentdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='USER', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
