# Generated by Django 3.1.4 on 2021-01-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_auto_20210116_1101'),
        ('class_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
