# Generated by Django 3.1.4 on 2021-01-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_auto_20210120_1825'),
        ('students_app', '0005_subject_score'),
        ('class_app', '0002_auto_20210116_1101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Class_Profile',
        ),
    ]
