# Generated by Django 3.1.4 on 2021-01-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210104_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='_class',
            new_name='clas_s',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='_subject',
            new_name='subject',
        ),
    ]
