# Generated by Django 3.1.4 on 2021-01-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210106_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='clas_s',
            new_name='Class',
        ),
    ]
