# Generated by Django 3.2.4 on 2021-08-11 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, default='House #10, Road #6, Australia', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fathersName',
            field=models.CharField(blank=True, default='Steve Jones', max_length=25),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='idNumber',
            field=models.CharField(blank=True, default='10005', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='joiningDate',
            field=models.DateTimeField(default='2021-08-10T20:45:51.667466Z'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mothersName',
            field=models.CharField(blank=True, default='Naomi Rose', max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, default='stevenjohnson@gmail.com', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, default='Steven Johnson', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='+ 88 98568888418', max_length=13),
        ),
        migrations.CreateModel(
            name='EducationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.userprofile')),
            ],
        ),
    ]
