# Generated by Django 3.2.4 on 2021-08-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210811_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
