# Generated by Django 3.2.4 on 2021-08-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_userprofile_joiningdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, default='stevenjohnson@gmail.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='joiningDate',
            field=models.DateField(blank=True, verbose_name='Joining-Date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='+ 88 98568888418', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prefix',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.')], max_length=4, null=True),
        ),
    ]
