# Generated by Django 3.2.4 on 2021-08-11 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='joiningDate',
            field=models.DateField(default=datetime.date(2021, 8, 11), verbose_name='Joining-Date'),
        ),
    ]
