# Generated by Django 3.2.4 on 2021-08-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_alter_userprofile_joiningdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='joiningDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
