# Generated by Django 3.2.4 on 2021-08-10 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_rename_departmentdetails_departmentdetail'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.departmentdetail'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.departmentdetail'),
        ),
    ]
