# Generated by Django 3.2.4 on 2021-08-18 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0005_auto_20210818_1447'),
        ('student', '0002_alter_academicdetails_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicdetails',
            name='score',
        ),
        migrations.RemoveField(
            model_name='academicdetails',
            name='subject',
        ),
        migrations.AddField(
            model_name='academicdetails',
            name='std',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='class_app.classdetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicdetails',
            name='subject1',
            field=models.CharField(default='00', max_length=3),
        ),
        migrations.AddField(
            model_name='academicdetails',
            name='subject2',
            field=models.CharField(default='00', max_length=3),
        ),
        migrations.AddField(
            model_name='academicdetails',
            name='subject3',
            field=models.CharField(default='00', max_length=3),
        ),
        migrations.AddField(
            model_name='academicdetails',
            name='subject4',
            field=models.CharField(default='00', max_length=3),
        ),
        migrations.AddField(
            model_name='academicdetails',
            name='subject5',
            field=models.CharField(default='00', max_length=3),
        ),
        migrations.AddField(
            model_name='academicdetails',
            name='subject6',
            field=models.CharField(default='00', max_length=3),
        ),
    ]
