# Generated by Django 3.2.4 on 2021-08-18 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0005_auto_20210818_1447'),
        ('student', '0003_auto_20210818_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.classdetail'),
        ),
    ]
