# Generated by Django 3.2.4 on 2021-08-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentdetails_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
