# Generated by Django 3.2.4 on 2021-08-18 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studentdetails_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdetails',
            name='student',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='student.studentdetails'),
        ),
    ]
