# Generated by Django 3.2.4 on 2021-08-18 20:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0005_auto_20210818_1447'),
        ('student', '0006_alter_academicdetails_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdetails',
            name='std',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='class_app.classdetail'),
        ),
        migrations.CreateModel(
            name='StudentAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('subject2', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('subject3', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('subject4', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('subject5', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('subject6', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.studentdetails')),
            ],
        ),
    ]
