# Generated by Django 3.2.4 on 2021-08-18 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210818_2043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentAttendence',
            new_name='StudentAttendance',
        ),
    ]
