# Generated by Django 3.2.4 on 2021-08-18 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0005_auto_20210818_1447'),
        ('student', '0008_rename_studentattendence_studentattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='std',
            field=models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, to='class_app.classdetail'),
            preserve_default=False,
        ),
    ]
