# Generated by Django 3.1.4 on 2021-01-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0001_initial'),
        ('students_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_login',
        ),
        migrations.AddField(
            model_name='profile',
            name='classes',
            field=models.ManyToManyField(to='class_app.Profile'),
        ),
    ]
