# Generated by Django 3.1.4 on 2021-01-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_auto_20210116_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='classes',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.')], max_length=4, null=True),
        ),
    ]
