# Generated by Django 3.1.4 on 2021-01-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0002_auto_20210116_1101'),
        ('students_app', '0004_profile_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=3, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.profile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.subject')),
            ],
        ),
    ]
