# Generated by Django 3.1.4 on 2021-01-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0003_auto_20210120_1825'),
        ('students_app', '0005_subject_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Student_Profile',
        ),
    ]
