# Generated by Django 3.1.4 on 2021-01-20 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0003_auto_20210120_1825'),
        ('students_app', '0006_auto_20210120_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_score',
            name='class_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='class_app.class_profile'),
        ),
    ]
