# Generated by Django 3.1.4 on 2021-01-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0007_subject_score_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_score',
            name='score',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
