# Generated by Django 3.1.4 on 2021-01-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0008_auto_20210122_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_profile',
            old_name='Class',
            new_name='class_name',
        ),
    ]
