# Generated by Django 3.1.4 on 2021-01-31 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0009_auto_20210124_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_score',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
