# Generated by Django 3.1.4 on 2021-01-07 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20210107_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.')], max_length=4, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.class')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='class.student_profile')),
                ('subject_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_1', to='accounts.subject')),
                ('subject_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_2', to='accounts.subject')),
                ('subject_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_3', to='accounts.subject')),
                ('subject_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_4', to='accounts.subject')),
            ],
        ),
    ]
