# Generated by Django 3.1.4 on 2021-01-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_auto_20210107_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='CLass',
            new_name='Class',
        ),
    ]
